# Generated by Django 5.0 on 2023-12-29 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_node_post_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#000000', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Prefix',
                'verbose_name_plural': 'Prefixes',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prefix'),
        ),
    ]
