# Generated by Django 5.0 on 2023-12-29 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prefix_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.node'),
        ),
    ]
