# Generated by Django 5.0 on 2023-12-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prefix_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
