# Generated by Django 5.0 on 2023-12-29 10:24

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usergroup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='access',
            field=models.ManyToManyField(blank=True, to='core.usergroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.ManyToManyField(blank=True, through='core.GroupMembership', to='core.usergroup'),
        ),
    ]
