# Generated by Django 5.0 on 2023-12-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usergroup_groupmembership_node_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='index',
        ),
    ]
