# Generated by Django 5.0 on 2023-12-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_forum_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='forum',
        ),
        migrations.AddField(
            model_name='forum',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='core.node'),
        ),
    ]
