# Generated by Django 5.0 on 2023-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_node_forum_forum_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='feather_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
