# Generated by Django 5.0 on 2023-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_forum_feather_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='feather_icon',
            field=models.CharField(blank=True, default='folder', max_length=200, null=True),
        ),
    ]
