# Generated by Django 5.0 on 2023-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_forum_feather_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['position'], 'verbose_name': 'Forum', 'verbose_name_plural': 'Forums'},
        ),
        migrations.AddField(
            model_name='forum',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
