# Generated by Django 5.0 on 2023-12-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
