# Generated by Django 5.0 on 2023-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_status_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('event', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='welcome/')),
                ('announcement_url', models.URLField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Welcome Message',
                'verbose_name_plural': 'Welcome Messages',
            },
        ),
    ]
