# Generated by Django 5.0 on 2023-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_post_replies_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
