# Generated by Django 5.0 on 2023-12-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_profile_is_online_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_italic',
            field=models.BooleanField(default=False),
        ),
    ]
