# Generated by Django 5.0 on 2023-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_usergroup_is_active_usergroup_is_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', max_length=200),
        ),
    ]
