# Generated by Django 5.0 on 2024-01-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_forum_slug_message_slug_node_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.AddField(
            model_name='node',
            name='children_nodes',
            field=models.ManyToManyField(blank=True, to='core.node'),
        ),
    ]
