# Generated by Django 5.0 on 2024-01-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_node_parent_node_children_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='nodes',
        ),
        migrations.AddField(
            model_name='node',
            name='parent_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.forum'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.node'),
        ),
    ]
