# Generated by Django 5.0 on 2024-01-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_forum_nodes_node_parent_forum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='display_description',
            field=models.BooleanField(default=True),
        ),
    ]
