# Generated by Django 5.0 on 2024-01-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_node_display_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
