# Generated by Django 5.0 on 2024-01-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_node_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['position'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='welcomemessages',
            options={'ordering': ['position'], 'verbose_name': 'Welcome Message', 'verbose_name_plural': 'Welcome Messages'},
        ),
        migrations.RemoveField(
            model_name='node',
            name='children_nodes',
        ),
        migrations.AlterField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_nodes', to='core.node'),
        ),
    ]
