# Generated by Django 5.0 on 2024-01-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_node_options_alter_welcomemessages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
