# Generated by Django 5.0 on 2024-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_node_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welcomemessages',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
