# Generated by Django 5.0 on 2024-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_post_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessages',
            name='is_centered',
            field=models.BooleanField(default=False),
        ),
    ]
