# Generated by Django 5.0 on 2024-01-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_welcomemessages_is_centered'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessages',
            name='url_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
