# Generated by Django 5.0 on 2024-01-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_welcomemessages_url_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessages',
            name='url_format',
            field=models.TextField(blank=True, help_text="Use 'ANNOUNCEMENT_URL' in the format, and it will be replaced with the actual link (Word: 'here').", max_length=200, null=True),
        ),
    ]
