# Generated by Django 5.0 on 2024-01-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_welcomemessages_url_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessages',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1920x1080', null=True, upload_to='welcome/'),
        ),
        migrations.AlterField(
            model_name='welcomemessages',
            name='is_centered',
            field=models.BooleanField(default=False, help_text='Center the message on the page if needed such as short message.'),
        ),
        migrations.AlterField(
            model_name='welcomemessages',
            name='message',
            field=models.TextField(help_text="Use 'USER' in the message, and it will be replaced with the user's name."),
        ),
        migrations.CreateModel(
            name='PreferenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_welcome_message', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
