# Generated by Django 5.0 on 2024-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_welcomemessages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_welcome_message',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PreferenceSettings',
        ),
    ]
